##########################################################################################
#
# SpringBoot 配置文件加载顺序
#
# SpringBoot 启动时会从以下位置
#
# file:./config/
# file:./
# classpath:/config/
# classpath:/
#
# 扫描application.properties或application.yml配置文件并全部加载作为默认配置文件
#其优先级由高到低,高优先级配置覆盖低优先级配置
#########################################################################################


# 项目启动时还可以通过命令行参数指定配置文件路径
#
# java -jar xxx.jar --spring.config.location=C:/Users/mac/Desktop/application.yml

##########################################################################################
# SpringBoot 外部配置加载顺序
#
# 01.命令行参数
# 02.java:comp/env的JNDI属性
# 03.java系统属性(System.getProperties())
# 04.操作系统环境变量
# 05.RandomValuePropertySource配置的random.*属性值
#
# 06.jar包外部的application-{profile}.properties或application-{profile}.yml配置文件
# 07.jar包内部的application-{profile}.properties或application-{profile}.yml配置文件
#
# 08.jar包外部的application.properties或application.yml配置文件
# 09.jar包内部的application.properties或application.yml配置文件
#
# 10.@Configuration注解类上的@PropertySource指定的配置文件
# 11.通过SpringApplication.setDefaultProperties指定的属性
#
# 以上配置优先级从高到底形成互补配置
##########################################################################################

server:
 port: 8081

